export const animals = [
  "Águia",
  "Baleia",
  "Búfalo",
  "Camaleão",
  "Camarão",
  "Canguru",
  "Capivara",
  "Caranguejo",
  "Cachorro",
  "Cisne",
  "Coelho",
  "Coruja",
  "Cobra",
  "Elefante",
  "Falcão",
  "Formiga",
  "Galinha",
  "Galo",
  "Gato",
  "Girafa",
  "Golfinho",
  "Gorila",
  "Hipopótamo",
  "Iguana",
  "Jaguar",
  "Koala",
  "Leão",
  "Lince",
  "Lontra",
  "Macaco",
  "Morcego",
  "Naja",
  "Panda",
  "Papagaio",
  "Pato",
  "Pavão",
  "Peixe",
  "Pinguim",
  "Puma",
  "Raposa",
  "Rato",
  "Rinoceronte",
  "Sapo",
  "Tartaruga",
  "Texugo",
  "Tubarão",
  "Urso",
  "Vaca",
  "Zebra"
];

export const stacks = [
  "Administração de Sistemas",
  "Análise de Dados",
  "Arquitetura de Software",
  "Automação",
  "Back-End",
  "Big Data",
  "Blockchain",
  "Business Intelligence",
  "Cloud Computing",
  "Cybersecurity",
  "Data Science",
  "Desenvolvimento de Jogos",
  "DevOps",
  "DevSecOps",
  "Engenharia de Dados",
  "Front-End",
  "FullStack",
  "Growth Hacking",
  "Inteligência Artificial",
  "Machine Learning",
  "Marketing Digital",
  "Mobile",
  "Product Management",
  "QA",
  "Redes e Infraestrutura",
  "Sales Engineer",
  "Suporte Técnico",
  "UX/UI"
];
